HumorProteomics/Controllers/ClinicalDataController.cs
using HumorProteomics.DbContext;
using HumorProteomics.Interface;
using HumorProteomics.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace HumorProteomics.Controllers
{
    public class ClinicalDataController : Controller
    {
        private readonly HumorDbContext _context;
        private readonly IClinicalData _clinicalData;
        public ClinicalDataController(IClinicalData ClinicalData, HumorDbContext context)
        {
            this._context = context;
            this._clinicalData = ClinicalData;
        }

        private SortModel ApplySort(string SortExpression)
        {
            ViewData["SortParamName"] = "Name";
            ViewData["SortParamDesc"] = "PortName";

            ViewData["SortIconName"] = "";
            ViewData["SortIconDesc"] = "";

            SortModel sortModel = new SortModel();

            switch (SortExpression.ToLower())
            {
                case "name_desc":
                    sortModel.SortedOrder = SortOrder.Descending;
                    sortModel.SortedProperty = "Name";
                    ViewData["SortParamName"] = "Name";
                    ViewData["SortIconName"] = "";
                    break;

                case "ProtName":
                    sortModel.SortedOrder = SortOrder.Ascending;
                    sortModel.SortedProperty = "ProtName";
                    ViewData["SortParamDesc"] = "ProtName";
                    break;

                case "ProtName_desc":
                    sortModel.SortedOrder = SortOrder.Descending;
                    sortModel.SortedProperty = "ProtName";
                    break;

                default:
                    sortModel.SortedOrder = SortOrder.Ascending;
                    sortModel.SortedProperty = "Name";
                    ViewData["SortIconName"] = "";
                    ViewData["SortParamName"] = "name_desc";
                    break;
            }
            return sortModel;
        }

        public IActionResult Default() 
        {
            ViewBag.datasource = _context.cd.Take(100).ToList();
            return View();
        }
        public IActionResult Index(string sortExpression = "", string SearchText = "", int pg = 1, int pageSize = 10)
        {
            SortModel sortModel = ApplySort(sortExpression);
            ViewBag.SearchText = SearchText;
            List<ClinicalData> clinidata = _clinicalData.GetAllClinicalData(sortModel.SortedProperty, sortModel.SortedOrder, SearchText,pg,pageSize);
            PaginatedList<ClinicalData> cldata = new PaginatedList<ClinicalData>(clinidata, pg, pageSize);
            var pager = new PagerModel(cldata.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;
            return View(cldata);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ClinicalData cldata)
        {
            try
            {
                _clinicalData.AddClinicalData(cldata);
                _context.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var clinicaldata = _clinicalData.GetClinicalDataById(id);
            return View(clinicaldata);
        }

        [HttpPost]
        public IActionResult Edit(ClinicalData cldata)
        {
            _clinicalData.UpdateClinicalData(cldata);
            _context.SaveChanges();
            return RedirectToAction(actionName: nameof(Index));
        }

        public IActionResult Details(int id)
        {
            var clinicaldata = _clinicalData.GetClinicalDataById(id);
            return View(clinicaldata);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var clinicaldata = _context.cd.Find(id);
            return View(clinicaldata);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            _clinicalData.DeleteClinicalData(id);
            _context.SaveChanges(true);
            return RedirectToAction(actionName: nameof(Index));
        }
    }
}

HumorProteomics/Controllers/ProteinDataController.cs
using HumorProteomics.DbContext;
using HumorProteomics.Interface;
using HumorProteomics.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace HumorProteomics.Controllers
{
    public class ProteinDataController : Controller
    {
        private readonly HumorDbContext _context;
        private readonly IProteinData _prodata;
        public ProteinDataController(IProteinData Prodata, HumorDbContext context)
        {
            this._context = context;
            this._prodata = Prodata;
        }

        private SortModel ApplySort(string SortExpression)
        {
            ViewData["SortParamName"] = "Name";
            ViewData["SortParamDesc"] = "PortName";

            ViewData["SortIconName"] = "";
            ViewData["SortIconDesc"] = "";

            SortModel sortModel = new SortModel();

            switch (SortExpression.ToLower())
            {
                case "name_desc":
                    sortModel.SortedOrder = SortOrder.Descending;
                    sortModel.SortedProperty = "Name";
                    ViewData["SortParamName"] = "Name";
                    ViewData["SortIconName"] = "";
                    break;

                case "ProtName":
                    sortModel.SortedOrder = SortOrder.Ascending;
                    sortModel.SortedProperty = "ProtName";
                    ViewData["SortParamDesc"] = "ProtName";
                    break;

                case "ProtName_desc":
                    sortModel.SortedOrder = SortOrder.Descending;
                    sortModel.SortedProperty = "ProtName";
                    break;

                default:
                    sortModel.SortedOrder = SortOrder.Ascending;
                    sortModel.SortedProperty = "Name";
                    ViewData["SortIconName"] = "";
                    ViewData["SortParamName"] = "name_desc";
                    break;
            }
            return sortModel;
        }
        public IActionResult Index(string sortExpression = "", string SearchText = "", int pg = 1, int pageSize = 10)
        {
            SortModel sortModel = ApplySort(sortExpression);
            ViewBag.SearchText = SearchText;
            List<ProteinData> proteinDat = _prodata.GetAllProteinData(sortModel.SortedProperty, sortModel.SortedOrder, SearchText,pg,pageSize);
            PaginatedList<ProteinData> proteinDatas = new PaginatedList<ProteinData>(proteinDat, pg, pageSize);
            var pager = new PagerModel(proteinDatas.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;
            return View(proteinDatas);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Create(ProteinData proteinData)
        {
            try
            {
                _prodata.AddProteinData(proteinData);
                _context.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var proteinData = _prodata.GetProteinDataById(id);
            return View(proteinData);
        }

        [HttpPost]
        public IActionResult Edit(ProteinData proteinData)
        {
            _prodata.UpdateProteinData(proteinData);
            _context.SaveChanges();
            return RedirectToAction(actionName: nameof(Index));
        }

        public IActionResult Details(int id)
        {
            var proteindata = _prodata.GetProteinDataById(id);
            return View(proteindata);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var proteindata = _context.pd.Find(id);
            return View(proteindata);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            _prodata.DeleteProteinData(id);
            _context.SaveChanges(true);
            return RedirectToAction(actionName: nameof(Index));
        }
    }
}

HumorProteomics/Controllers/ProteinSummaryController.cs
using HumorProteomics.DbContext;
using HumorProteomics.Interface;
using HumorProteomics.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace HumorProteomics.Controllers
{
    public class ProteinSummaryController : Controller
    {
        private readonly HumorDbContext  _context;
        private readonly IProteinSummary _prosum;
        public ProteinSummaryController(IProteinSummary prosum, HumorDbContext context)
        {
            this._context = context;
            this._prosum = prosum;
        }

        private SortModel ApplySort(string SortExpression) 
        {
            ViewData["SortParamName"] = "Name";
            ViewData["SortParamDesc"] = "PortName";

            ViewData["SortIconName"] = "";
            ViewData["SortIconDesc"] = "";

            SortModel sortModel = new SortModel();

            switch (SortExpression.ToLower()) 
            {
                case "name_desc":
                    sortModel.SortedOrder = SortOrder.Descending;
                    sortModel.SortedProperty = "Name";
                    ViewData["SortParamName"] = "Name";
                    ViewData["SortIconName"] = "";
                    break;

                case "ProtName":
                    sortModel.SortedOrder = SortOrder.Ascending;
                    sortModel.SortedProperty = "ProtName";
                    ViewData["SortParamDesc"] = "ProtName";
                    break ;

                case "ProtName_desc":
                    sortModel.SortedOrder = SortOrder.Descending;
                    sortModel.SortedProperty = "ProtName";
                    break;

                default:
                    sortModel.SortedOrder = SortOrder.Ascending;
                    sortModel.SortedProperty = "Name";
                    ViewData["SortIconName"] = "";
                    ViewData["SortParamName"] = "name_desc";
                    break;
            }
            return sortModel;
        }


        public IActionResult Index(string sortExpression="", string SearchText="", int pg=1 ,int pageSize =10)
        {
            SortModel sortModel = ApplySort(sortExpression);
            ViewBag.SearchText = SearchText;
            List<ProteinSummary> prosm = _prosum.GetAllProteinSummary(sortModel.SortedProperty,sortModel.SortedOrder, SearchText, pg, pageSize);
            PaginatedList<ProteinSummary> proteinsum = new PaginatedList<ProteinSummary>(prosm, pg, pageSize);
            var pager = new PagerModel(proteinsum.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;
            return View(proteinsum);
        }

        [HttpGet]
        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProteinSummary prosum) 
        {
            try
            {
                _prosum.AddProteinSummary(prosum);
                _context.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id) 
        {
            var proteinsummary = _prosum.GetProteinSummaryById(id);
            return View(proteinsummary);
        }

        [HttpPost]
        public IActionResult Edit(ProteinSummary prosum) 
        {
            _prosum.UpdateProteinSummary(prosum);
            _context.SaveChanges();
            return RedirectToAction(actionName: nameof(Index));
        }

        public IActionResult Details(int id) 
        {
            var proteinsummary = _prosum.GetProteinSummaryById(id);
            return View(proteinsummary);
        }

        [HttpGet]
        public IActionResult Delete(int? id) 
        {
            if (id == null)
            {
                return NotFound();
            }
            var proteinsummary = _context.ps.Find(id);
            return View(proteinsummary);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult ConfirmDelete(int id) 
        {
            _prosum.DeleteProteinSummary(id);
            _context.SaveChanges(true);
            return RedirectToAction(actionName: nameof(Index));
        }
    }
}

HumorProteomics/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HumorProteomics.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-info border-bottom box-shadow mb-4" style="background-color:rgb(65,152,199)">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ProteinSummary" asp-action="Index">Protein Summary</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ProteinData" asp-action="Index">Protein Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ClinicalData" asp-action="Index">Clinical Data</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Deshboard</a>
                            </li>
                        }

                    </ul>
                </div>
                <partial name="_loginPartial.cshtml">
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted" style="font-size:medium;">
        <div class="container" style="text-align:center;">
            <span style="font-size:18px; color:black;)">&copy;Synergy Sail Technology Limited</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/0f92dff671.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HumorProteomics/Views/Shared/_bottomBar.cshtml
@model PagerModel

<div class="container m-0 p-0 btn-group" style="background-color:rgb(65,152,199); border-radius:10px; height:45px; color:white;">

    <div class="col-4 btn-group p-1 m-1">
        <p>
            Showing @Model.StartRecord to @Model.EndRecord of @Model.TotalItems Rows
        </p>
    </div>

    <div class="col-4 btn-group justify-content-center">
        <span class="col-4 mt-1 p-0">
            Rows Per Page 
        </span>
        <span class="col-3 p-0">
            <select class="form-control" id="pageSelector" asp-items="Model.GetPageSize()"></select>
        </span>
    </div> 

    <div class="col-2 btn-group justify-content-end">
        <p>
            Showing @Model.CurrentPage/@Model.TotalPages Rows 
        </p>
    </div>
</div>

HumorProteomics/Views/Shared/_topBar.cshtml
@model PagerModel

<style>
    .page-link{color:black!important;}
    .page-link.active .page-link{
     z-index:3;
     color:#fff;
     background-color:white!important;
     border-color:seagreen;
    }

</style>

<div class="container btn-group" " style="background-color:rgb(65,152,199); border-radius:18px; height:45px">
    <div class="col-4 p-0 justify-content-end mt-1">
        <form asp-action="Index">
            <span class="btn-group">
                <input class="form-control" type="text"
                name="SearchText"
                value="@ViewBag.SearchText"
                placeholder="Search Key"/>
            <input class="p-1 ml-2 btn btn-sm btn-danger" style="border-radius:10px"/>
            </span>
        </form>
    </div>
    <div class="container ml-1">
        <ul class="pagination justify-content-end">
            @if (Model.CurrentPage> 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action" 
                    asp-route-pg="1"
                    asp-route-pageSize="@Model.PageSize"
                    asp-route-SearchText="@Model.SearchText"
                    asp-route-SortExpression="@Model.SortExpression">
                    First
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                    asp-route-pg="@(Model.CurrentPage-1)"
                    asp-route-pageSize="@Model.PageSize"
                    asp-route-SeatchText="@Model.SearchText"
                    asp-route-SortExpression="@Model.SortExpression">
                    Previous
                    </a>
                </li>
            }
            @for (int pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge==Model.CurrentPage ? "active":"")">
                    @if (pge!=Model.CurrentPage)
                    {
                        <a class="page-link" asp-action="@Model.Action"
                        asp-route-pg="@pge"
                        asp-route-pageSize="@Model.PageSize"
                        asp-route-SearchText="@Model.SearchText"
                        asp-route-sortExpression="@Model.SortExpression">
                        @pge
                        </a>
                    }
                    else
                    {
                        <span class="page-link">@pge</span>
                    }
                </li>
            }
            @if (Model.CurrentPage <Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                    asp-route-pg="@(Model.CurrentPage + 1)"
                    asp-route-pageSize="@Model.PageSize"
                    asp-route-SearchText="@Model.SearchText"
                    asp-route-sortExpression="@Model.SortExpression">
                    Next    
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                    asp-route-pg="@(Model.TotalPages)"
                    asp-route-pageSize="@Model.PageSize"
                    asp-route-SearchText="@Model.SearchText"
                    asp-route-SortExpression="@Model.SortExpression">
                    Last
                    </a>
                </li>
            }
        </ul>
    </div>
</div>